# Generated by Django 6.0 on 2025-12-31 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='herotext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('toptext', models.CharField(max_length=30)),
                ('hero_title', models.CharField(max_length=200)),
                ('hero_description', models.CharField(max_length=300)),
            ],
        ),
    ]
