# Generated by Django 6.0 on 2025-12-31 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contentcolumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='content/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
