# Generated by Django 6.0 on 2025-12-31 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0002_contentcolumn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='certifications/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
