# Generated by Django 6.0 on 2025-12-31 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0003_certification'),
    ]

    operations = [
        migrations.CreateModel(
            name='contentbody',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='contentbody/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='herotext',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
