# Generated by Django 6.0 on 2026-01-01 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0006_footer'),
    ]

    operations = [
        migrations.CreateModel(
            name='comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labels', models.CharField(max_length=200)),
                ('teacher', models.TextField()),
                ('others', models.TextField()),
            ],
        ),
    ]
