# Generated by Django 6.0 on 2026-01-01 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0007_comparison'),
    ]

    operations = [
        migrations.AddField(
            model_name='comparison',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
