# Generated by Django 6.0 on 2026-01-02 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0008_comparison_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='whyus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('images', models.ImageField(upload_to='whyus/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
