# Generated by Django 6.0 on 2026-01-05 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TeacherApp', '0010_alter_certification_image_alter_contentbody_image_and_more'),
        ('TeacherApp', '0010_remove_whyus_images_whyus_image_and_more'),
    ]

    operations = [
    ]
